name: flashdrop
description: "Fast, Private, Offline File Transfer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # File System
  file_picker: ^8.1.4
  path_provider: ^2.1.1
  permission_handler: ^11.1.0

  # Network
  network_info_plus: ^5.0.1

  # UI
  google_fonts: ^6.1.0

  # Utilities
  uuid: ^4.2.2
  crypto: ^3.0.3
  
  # Database for history
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4

  # Platform
  device_info_plus: ^9.1.1
  path: ^1.9.1

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3

  # Window Manager (Windows desktop)
  window_manager: ^0.3.8

  # Bluetooth (Android only)
  flutter_bluetooth_serial: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
